config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "calendars#index"
  get 'calendars/calendar_data', to: 'calendars#calendar_data'
  get 'calendars/full_plan', to: 'calendars#full_plan'
  post 'calendars/save_content', to: 'calendars#save_content'
  post 'calendars/delete_content', to: 'calendars#delete_content'
  get 'calendars/next_calendar_data', to: 'calendars#next_calendar_data'
  get 'calendars/last_calendar_data', to: 'calendars#last_calendar_data'
  resources :calendars, only: [:index,:show]
  resources :users, only: :show do
    member do
      get 'show_calc'
      get 'show_toDo'
    end
  end

  post 'households/save_data', to: 'households#save_data'
  get 'households/index_data', to: 'households#index_data'
  post 'households/delete_data', to: 'households#delete_data'
  
  post 'to_dos/save_data', to: 'to_dos#save_data'
  post 'to_dos/delete_data', to: 'to_dos#delete_data'
  get 'to_dos/index_data', to: 'to_dos#index_data'
end

app/models/calendar.rb
class Calendar < ApplicationRecord
    belongs_to :user
    
    with_options presence: true do
        validates :date
        validates :content
    end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  require "date"

  def index
    @year_time = Time.now.year
    @month_time = Time.now.month
    @date_time = Time.now.day
  end

  def calendar_data
    # 現在の年月を取得してカレンダーデータを生成 ⇒ 送られてきたパラメータに応じて年月を取得へ変更5/25
    year = params[:year].to_i
    month = params[:month].to_i
    year = Time.now.year if year == 0
    month = Time.now.month if month == 0

    render_calendar(year,month)
  end

  def full_plan
    today_year = Time.now.year
    today_month = Time.now.month
    today_day = Time.now.day

    today_date = Date.new(today_year,today_month,today_day)

    events = current_user.calendars.where("date >= ?",today_date)
    event_data = events.map { |event| { year: event.date.year, month: event.date.month, date: event.date.day, content: event.content } }
    new_events = event_data.sort_by{ |i| [i[:year], i[:month], i[:date]] }

    render json: { events: new_events }
  end

  def save_content
    year = params[:event][:year].to_i
    month = params[:event][:month].to_i
    day = params[:event][:date].to_i
    content = params[:event][:content]

    date = Date.new(year, month, day)
    
    if current_user.calendars.find_by(date: date).present?
      calendar = current_user.calendars.find_by(date: date)
      if calendar.update(content: content)
        render json: { status: "success", message: "Content saved successfully." }, status: :ok
      else
        render json: { status: "error", errors: calendar.errors.full_messages }, status: :unprocessable_entity
      end
    else
      calendar = current_user.calendars.new(
        date: date,
        content: params[:event][:content]
      )
      if calendar.save
        render json: { status: "success", message: "Content saved successfully." }, status: :ok
      else
        render json: { status: "error", errors: calendar.errors.full_messages }, status: :unprocessable_entity
      end
    end
  end

  def delete_content
    year = params[:event][:year].to_i
    month = params[:event][:month].to_i
    day = params[:event][:date].to_i

    calendars = current_user.calendars.where(date: Date.new(year, month, day))
    
    errors = []

    calendars.each do |calendar|
      unless calendar.destroy
        errors << calendar.errors.full_messages
      end
    end

    if errors.empty?
      render json: { status: "success", message: "All content deleted successfully." }, status: :ok
    else
      render json: { status: "error", errors: errors.flatten }, status: :unprocessable_entity
    end
  end

  def next_calendar_data
     # 現在の年月を取得してカレンダーデータを生成 ⇒ 送られてきたパラメータに応じて年月を取得へ変更5/25
    year = params[:year].to_i
    month = params[:month].to_i

    if month > 12
      month = 1
      year = year + 1
    end     
 
    render_calendar(year,month)
  end

  def last_calendar_data
     # 現在の年月を取得してカレンダーデータを生成 ⇒ 送られてきたパラメータに応じて年月を取得へ変更5/25
    year = params[:year].to_i
    month = params[:month].to_i

    if month < 1
      month = 12
      year = year - 1
    end     
 
    render_calendar(year,month)
  end

  private

  def event_params
    params.require(:event).permit(:date, :content).merge(user_id: current_user.id)
  end

  def render_calendar(year,month)
    push = Push.new(year, month)
    calendar_data = push.array_pass
     
    events = current_user.calendars.where(date: Date.new(year, month, 1)..Date.new(year, month, -1))
    event_data = events.map { |event| { year: event.date.year, month: event.date.month, date: event.date.day, content: event.content } }
 
    render json: { calendar: calendar_data, events: event_data }
  end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/index.html.erb
<body class="first">
  
  <%= render "shared/header" %>
  <main class="top-view">
    <% if user_signed_in? %>
    <div class="main-visual top-content">
      <h2>Hello Boss</h2>
      <h2 class="times" >本日は<%= @year_time %>年<%= @month_time %>月<%= @date_time %>日です。</h2>
      <p>すてきな１日を</p>
      <div class="btn-wrapper">
        <%= link_to "マイページ", user_path(current_user.id), class: "my-page-btn"%>
      </div>
      <div class="btn-wrapper">
        <%= link_to "家計簿ページ", show_calc_user_path(current_user.id), class: "my-page-btn"%>
      </div>
      <div>
        <%= link_to "to-doリスト(工事中)", show_toDo_user_path(current_user.id), class: "my-page-btn"%>
      </div>
    </div>

    <% else %>
    
    <div class="first-view">
      <div class="first-image">
        <%= image_tag "design.png" %>
      </div>
      <div class="first-logo">
        <h2>あなたの毎日を足跡に</h2>
        <div class="design-image-first">
          <%= image_tag "toppage.png" %>
        </div>
        <div class="design-image-second">
          <%= image_tag "calendar_page.png" %>
        </div>
      </div>
    </div>
    <div class="second-view">
      <div class="second-logo">
        <h2>予定も家計簿も思いのまま</h2>
        <div class="design-image-first">
          <%= image_tag "plan_list.png" %>
          
        </div>
        <div class="design-image-second">
          
          <%= image_tag "my_payment_page.png" %>
        </div>
      </div>
      <div class="second-image">
        <%= image_tag "many-clocks.png" %>
      </div>
    </div>
    <div class="third-view">
      <h2>最高の<span>Experience</span>を</h2>
      <p>さあ、始めよう</p>
      <%= link_to '新規登録', new_user_registration_path, class: "first-sign-up" %>
    </div>

    <% end %>
  </main>
</body>